In [1]:
import pandas as pd
import os

In [2]:
df=pd.read_csv("RQ2_result.csv")

In [3]:
df.head()

,Unnamed: 0,env,rewardfun,agent,rewards,rewards_variance,durations,detected,missed,ttf,napfd,recall,avg_precision,step
0,0,apache_commons,add_tcfail_1,mlp_cla_new,0.009511,0.018671,0.103617,2.253571,0.032143,226.110714,0.524835,0.981548,123.0,134.428571
1,1,apache_commons,add_tcfail_2,mlp_cla_new,0.010077,0.020741,0.110774,2.257143,0.028571,281.464286,0.427183,0.990476,123.0,134.428571
2,2,apache_commons,add_tcfail_3,mlp_cla_new,0.010798,0.024299,0.107117,2.282143,0.003571,238.769048,0.505199,0.998016,123.0,134.428571
3,3,apache_commons,tcfail,mlp_cla_new,0.008268,0.016440,0.101994,2.075000,0.210714,336.729762,0.276264,0.929762,123.0,134.428571
4,4,apache_drill,add_tcfail_1,mlp_cla_new,0.304724,0.355454,0.024828,4.534615,3.273077,4.307692,0.564677,0.749803,123.0,100.884615

# 内容提取

In [4]:
def analysis_noth(df):
    
    reward_list=["tcfail","add_tcfail_1","add_tcfail_2","add_tcfail_3"]
    exlist=["Dataset"]+reward_list*4
    lista=[] 
    for column, env in enumerate(sorted(df['env'].unique())):
        env1=env.title()
        env1=env1.replace("_"," ")
        if env1=="Iofrol":
            env1="IOF/ROL"
        slist=[env1]
            #for re in ["APHF","failcount","tcfail","timerank"]:
        for title in ['napfd','recall','ttf','durations']:
            for re in reward_list:
            
                tdf=df[df["rewardfun"].isin([re]) & df["env"].isin([env])]
                x=str(tdf[title]).split()[1]
                #print(x)
                slist.append(float(x))
                
        lista.append(slist)
    
    

    
    #print(exlist)
    # list转dataframe
    cdf = pd.DataFrame(lista, columns=exlist)

    # 保存到本地excel
    cdf.to_excel("qr2_.xlsx", index=False)

In [5]:
analysis_noth(df)